-- HopeHouse initial Prisma/PostgreSQL persistence migration.
-- Prisma DateTime fields are explicitly mapped to PostgreSQL TIMESTAMPTZ(3).
-- PostgreSQL-only contracts are preserved manually.

CREATE TYPE "UserStatus" AS ENUM ('active', 'inactive', 'suspended', 'archived');
CREATE TYPE "CredentialStatus" AS ENUM ('active', 'disabled', 'rotated', 'archived');
CREATE TYPE "DeviceStatus" AS ENUM ('pending', 'trusted', 'untrusted', 'revoked', 'archived');
CREATE TYPE "SessionStatus" AS ENUM ('active', 'revoked', 'expired', 'archived');
CREATE TYPE "RefreshTokenStatus" AS ENUM ('active', 'rotated', 'revoked', 'expired', 'reused');
CREATE TYPE "LoginAttemptOutcome" AS ENUM ('succeeded', 'failed', 'blocked');
CREATE TYPE "SecurityEventSeverity" AS ENUM ('info', 'medium', 'major', 'critical');
CREATE TYPE "PasswordResetStatus" AS ENUM ('pending', 'completed', 'expired', 'revoked');
CREATE TYPE "TwoFactorSettingStatus" AS ENUM ('active', 'inactive', 'archived');
CREATE TYPE "TwoFactorChallengeStatus" AS ENUM ('pending', 'succeeded', 'failed', 'expired');
CREATE TYPE "AppSettingStatus" AS ENUM ('draft', 'active', 'archived');

CREATE TABLE "roles" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT NOT NULL, CONSTRAINT "roles_pkey" PRIMARY KEY ("id"));
CREATE TABLE "users" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "display_name" TEXT NOT NULL, "status" "UserStatus" NOT NULL, "role_id" TEXT NOT NULL, "created_at" TIMESTAMPTZ(3) NOT NULL, "updated_at" TIMESTAMPTZ(3) NOT NULL, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
CREATE TABLE "app_settings" ("id" TEXT NOT NULL, "namespace" TEXT NOT NULL, "key" TEXT NOT NULL, "scope_type" TEXT NOT NULL, "scope_id" TEXT, "status" "AppSettingStatus" NOT NULL, "value_json" JSONB NOT NULL, "starts_at" TIMESTAMPTZ(3), "ends_at" TIMESTAMPTZ(3), "created_by_user_id" TEXT, "updated_by_user_id" TEXT, "created_at" TIMESTAMPTZ(3) NOT NULL, "updated_at" TIMESTAMPTZ(3) NOT NULL, "metadata_json" JSONB NOT NULL, CONSTRAINT "app_settings_pkey" PRIMARY KEY ("id"), CONSTRAINT "app_settings_scope_type_scope_id_check" CHECK (("scope_type" = 'global' AND "scope_id" IS NULL) OR ("scope_type" <> 'global' AND "scope_id" IS NOT NULL)));
CREATE TABLE "auth_credentials" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "credential_type" TEXT NOT NULL, "credential_hash" TEXT NOT NULL, "status" "CredentialStatus" NOT NULL, "last_changed_at" TIMESTAMPTZ(3) NOT NULL, "must_rotate_at" TIMESTAMPTZ(3), "created_at" TIMESTAMPTZ(3) NOT NULL, "updated_at" TIMESTAMPTZ(3) NOT NULL, "metadata_json" JSONB NOT NULL, CONSTRAINT "auth_credentials_pkey" PRIMARY KEY ("id"));
CREATE TABLE "device_fingerprints" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "fingerprint_hash" TEXT NOT NULL, "label" TEXT, "status" "DeviceStatus" NOT NULL, "first_seen_at" TIMESTAMPTZ(3) NOT NULL, "last_seen_at" TIMESTAMPTZ(3) NOT NULL, "revoked_at" TIMESTAMPTZ(3), "revoked_by_user_id" TEXT, "metadata_json" JSONB NOT NULL, CONSTRAINT "device_fingerprints_pkey" PRIMARY KEY ("id"));
CREATE TABLE "login_sessions" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "device_fingerprint_id" TEXT, "status" "SessionStatus" NOT NULL, "issued_at" TIMESTAMPTZ(3) NOT NULL, "expires_at" TIMESTAMPTZ(3) NOT NULL, "idle_expires_at" TIMESTAMPTZ(3), "last_seen_at" TIMESTAMPTZ(3), "revoked_at" TIMESTAMPTZ(3), "revoked_by_user_id" TEXT, "revocation_reason" TEXT, "metadata_json" JSONB NOT NULL, CONSTRAINT "login_sessions_pkey" PRIMARY KEY ("id"));
CREATE TABLE "session_refresh_tokens" ("id" TEXT NOT NULL, "session_id" TEXT NOT NULL, "token_hash" TEXT NOT NULL, "status" "RefreshTokenStatus" NOT NULL, "issued_at" TIMESTAMPTZ(3) NOT NULL, "expires_at" TIMESTAMPTZ(3) NOT NULL, "rotated_at" TIMESTAMPTZ(3), "revoked_at" TIMESTAMPTZ(3), "replaced_by_token_id" TEXT, "metadata_json" JSONB NOT NULL, CONSTRAINT "session_refresh_tokens_pkey" PRIMARY KEY ("id"));
CREATE TABLE "login_attempts" ("id" TEXT NOT NULL, "user_id" TEXT, "identifier_hash" TEXT NOT NULL, "device_fingerprint_id" TEXT, "ip_address_hash" TEXT, "outcome" "LoginAttemptOutcome" NOT NULL, "failure_reason" TEXT, "occurred_at" TIMESTAMPTZ(3) NOT NULL, "metadata_json" JSONB NOT NULL, CONSTRAINT "login_attempts_pkey" PRIMARY KEY ("id"));
CREATE TABLE "security_events" ("id" TEXT NOT NULL, "user_id" TEXT, "actor_user_id" TEXT, "event_type" TEXT NOT NULL, "severity" "SecurityEventSeverity" NOT NULL, "related_entity_type" TEXT, "related_entity_id" TEXT, "occurred_at" TIMESTAMPTZ(3) NOT NULL, "metadata_json" JSONB NOT NULL, CONSTRAINT "security_events_pkey" PRIMARY KEY ("id"));
CREATE TABLE "password_reset_requests" ("id" TEXT NOT NULL, "user_id" TEXT, "identifier_hash" TEXT NOT NULL, "token_hash" TEXT NOT NULL, "status" "PasswordResetStatus" NOT NULL, "expires_at" TIMESTAMPTZ(3) NOT NULL, "completed_at" TIMESTAMPTZ(3), "created_at" TIMESTAMPTZ(3) NOT NULL, "metadata_json" JSONB NOT NULL, CONSTRAINT "password_reset_requests_pkey" PRIMARY KEY ("id"));
CREATE TABLE "two_factor_settings" ("id" TEXT NOT NULL, "scope_type" TEXT NOT NULL, "scope_id" TEXT, "method" TEXT NOT NULL, "status" "TwoFactorSettingStatus" NOT NULL, "configuration_json" JSONB NOT NULL, "created_at" TIMESTAMPTZ(3) NOT NULL, "updated_at" TIMESTAMPTZ(3) NOT NULL, "metadata_json" JSONB NOT NULL, CONSTRAINT "two_factor_settings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "two_factor_challenges" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "session_id" TEXT, "action" TEXT NOT NULL, "method" TEXT NOT NULL, "challenge_hash" TEXT, "status" "TwoFactorChallengeStatus" NOT NULL, "attempt_count" INTEGER NOT NULL, "max_attempts" INTEGER NOT NULL, "expires_at" TIMESTAMPTZ(3) NOT NULL, "verified_at" TIMESTAMPTZ(3), "created_at" TIMESTAMPTZ(3) NOT NULL, "updated_at" TIMESTAMPTZ(3) NOT NULL, "metadata_json" JSONB NOT NULL, CONSTRAINT "two_factor_challenges_pkey" PRIMARY KEY ("id"), CONSTRAINT "two_factor_challenges_attempt_count_check" CHECK ("attempt_count" >= 0), CONSTRAINT "two_factor_challenges_max_attempts_check" CHECK ("max_attempts" > 0));
CREATE TABLE "admin_access_logs" ("id" TEXT NOT NULL, "actor_user_id" TEXT NOT NULL, "target_user_id" TEXT, "action" TEXT NOT NULL, "reason" TEXT NOT NULL, "session_id" TEXT, "started_at" TIMESTAMPTZ(3) NOT NULL, "ended_at" TIMESTAMPTZ(3), "metadata_json" JSONB NOT NULL, CONSTRAINT "admin_access_logs_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "roles_name_key" ON "roles"("name");
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE INDEX "users_status_idx" ON "users"("status");
CREATE INDEX "users_role_id_idx" ON "users"("role_id");
CREATE UNIQUE INDEX "app_settings_unique_identity" ON "app_settings"("namespace", "key", "scope_type", "scope_id", "status") NULLS NOT DISTINCT;
CREATE INDEX "app_settings_namespace_key_scope_id_status_idx" ON "app_settings"("namespace", "key", "scope_type", "scope_id", "status");
CREATE INDEX "app_settings_namespace_key_status_idx" ON "app_settings"("namespace", "key", "status");
CREATE INDEX "app_settings_scope_type_scope_id_status_idx" ON "app_settings"("scope_type", "scope_id", "status");
CREATE INDEX "app_settings_starts_at_ends_at_idx" ON "app_settings"("starts_at", "ends_at");
CREATE INDEX "auth_credentials_user_id_credential_type_status_idx" ON "auth_credentials"("user_id", "credential_type", "status");
CREATE INDEX "auth_credentials_must_rotate_at_idx" ON "auth_credentials"("must_rotate_at");
CREATE UNIQUE INDEX "device_fingerprints_user_id_fingerprint_hash_key" ON "device_fingerprints"("user_id", "fingerprint_hash");
CREATE INDEX "device_fingerprints_user_id_status_idx" ON "device_fingerprints"("user_id", "status");
CREATE INDEX "device_fingerprints_last_seen_at_idx" ON "device_fingerprints"("last_seen_at");
CREATE INDEX "device_fingerprints_revoked_at_idx" ON "device_fingerprints"("revoked_at");
CREATE INDEX "login_sessions_user_id_status_idx" ON "login_sessions"("user_id", "status");
CREATE INDEX "login_sessions_device_fingerprint_id_status_idx" ON "login_sessions"("device_fingerprint_id", "status");
CREATE INDEX "login_sessions_expires_at_idx" ON "login_sessions"("expires_at");
CREATE INDEX "login_sessions_idle_expires_at_idx" ON "login_sessions"("idle_expires_at");
CREATE INDEX "login_sessions_revoked_at_idx" ON "login_sessions"("revoked_at");
CREATE UNIQUE INDEX "session_refresh_tokens_token_hash_key" ON "session_refresh_tokens"("token_hash");
CREATE INDEX "session_refresh_tokens_session_id_status_idx" ON "session_refresh_tokens"("session_id", "status");
CREATE INDEX "session_refresh_tokens_expires_at_idx" ON "session_refresh_tokens"("expires_at");
CREATE INDEX "session_refresh_tokens_replaced_by_token_id_idx" ON "session_refresh_tokens"("replaced_by_token_id");
CREATE INDEX "login_attempts_identifier_hash_outcome_occurred_at_idx" ON "login_attempts"("identifier_hash", "outcome", "occurred_at");
CREATE INDEX "login_attempts_user_id_occurred_at_idx" ON "login_attempts"("user_id", "occurred_at");
CREATE INDEX "login_attempts_ip_address_hash_occurred_at_idx" ON "login_attempts"("ip_address_hash", "occurred_at");
CREATE INDEX "login_attempts_device_fingerprint_id_occurred_at_idx" ON "login_attempts"("device_fingerprint_id", "occurred_at");
CREATE INDEX "security_events_user_id_occurred_at_idx" ON "security_events"("user_id", "occurred_at");
CREATE INDEX "security_events_actor_user_id_occurred_at_idx" ON "security_events"("actor_user_id", "occurred_at");
CREATE INDEX "security_events_event_type_occurred_at_idx" ON "security_events"("event_type", "occurred_at");
CREATE INDEX "security_events_severity_occurred_at_idx" ON "security_events"("severity", "occurred_at");
CREATE INDEX "security_events_related_entity_type_related_entity_id_idx" ON "security_events"("related_entity_type", "related_entity_id");
CREATE UNIQUE INDEX "password_reset_requests_token_hash_key" ON "password_reset_requests"("token_hash");
CREATE INDEX "password_reset_requests_identifier_hash_created_at_idx" ON "password_reset_requests"("identifier_hash", "created_at");
CREATE INDEX "password_reset_requests_user_id_status_created_at_idx" ON "password_reset_requests"("user_id", "status", "created_at");
CREATE INDEX "password_reset_requests_status_expires_at_idx" ON "password_reset_requests"("status", "expires_at");
CREATE INDEX "two_factor_settings_scope_type_scope_id_status_idx" ON "two_factor_settings"("scope_type", "scope_id", "status");
CREATE INDEX "two_factor_settings_method_status_idx" ON "two_factor_settings"("method", "status");
CREATE INDEX "two_factor_challenges_user_id_status_created_at_idx" ON "two_factor_challenges"("user_id", "status", "created_at");
CREATE INDEX "two_factor_challenges_status_expires_at_idx" ON "two_factor_challenges"("status", "expires_at");
CREATE INDEX "two_factor_challenges_session_id_idx" ON "two_factor_challenges"("session_id");
CREATE INDEX "two_factor_challenges_action_status_created_at_idx" ON "two_factor_challenges"("action", "status", "created_at");
CREATE INDEX "admin_access_logs_actor_user_id_started_at_idx" ON "admin_access_logs"("actor_user_id", "started_at");
CREATE INDEX "admin_access_logs_target_user_id_started_at_idx" ON "admin_access_logs"("target_user_id", "started_at");
CREATE INDEX "admin_access_logs_action_started_at_idx" ON "admin_access_logs"("action", "started_at");
CREATE INDEX "admin_access_logs_session_id_idx" ON "admin_access_logs"("session_id");

ALTER TABLE "users" ADD CONSTRAINT "users_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "app_settings" ADD CONSTRAINT "app_settings_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "app_settings" ADD CONSTRAINT "app_settings_updated_by_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "auth_credentials" ADD CONSTRAINT "auth_credentials_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "device_fingerprints" ADD CONSTRAINT "device_fingerprints_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "device_fingerprints" ADD CONSTRAINT "device_fingerprints_revoked_by_user_id_fkey" FOREIGN KEY ("revoked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "login_sessions" ADD CONSTRAINT "login_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "login_sessions" ADD CONSTRAINT "login_sessions_device_fingerprint_id_fkey" FOREIGN KEY ("device_fingerprint_id") REFERENCES "device_fingerprints"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "login_sessions" ADD CONSTRAINT "login_sessions_revoked_by_user_id_fkey" FOREIGN KEY ("revoked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "session_refresh_tokens" ADD CONSTRAINT "session_refresh_tokens_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "login_sessions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "session_refresh_tokens" ADD CONSTRAINT "session_refresh_tokens_replaced_by_token_id_fkey" FOREIGN KEY ("replaced_by_token_id") REFERENCES "session_refresh_tokens"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "login_attempts" ADD CONSTRAINT "login_attempts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "login_attempts" ADD CONSTRAINT "login_attempts_device_fingerprint_id_fkey" FOREIGN KEY ("device_fingerprint_id") REFERENCES "device_fingerprints"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "security_events" ADD CONSTRAINT "security_events_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "security_events" ADD CONSTRAINT "security_events_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "password_reset_requests" ADD CONSTRAINT "password_reset_requests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "two_factor_challenges" ADD CONSTRAINT "two_factor_challenges_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "two_factor_challenges" ADD CONSTRAINT "two_factor_challenges_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "login_sessions"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "admin_access_logs" ADD CONSTRAINT "admin_access_logs_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "admin_access_logs" ADD CONSTRAINT "admin_access_logs_target_user_id_fkey" FOREIGN KEY ("target_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "admin_access_logs" ADD CONSTRAINT "admin_access_logs_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "login_sessions"("id") ON DELETE SET NULL ON UPDATE CASCADE;
